### ISSUE TITLE
adb and Digital Paper App

### ISSUE THREAD

**Issue by ghostwheel** [HappyZ/dpt-tools#132]
My RP1 was rooted/upgraded. I might have an old version or the hack, since I did it pretty early.

For some reason, adb doesn't work. Instead, the Digital Papers app can connect to my reader through USB. I actually like it, because I can leave WiFi off, and sync when I want, while changing.
But, I can't run adb. When I type adb on my windows machine, it doesn't see the RP1.

My question is: is it possible to have both adb working, and connect to the app using usb? If not, is it possible to switch between them?

**Comment by ghostwheel** [comment]
My RP1 was rooted/upgraded. I might have an old version or the hack, since I did it pretty early.

 For some reason, adb doesn't work. Instead, the Digital Papers app can connect to my reader through USB. I actually like it, because I can leave WiFi off, and sync when I want, while changing.
But, I can't run adb. When I type adb on my windows machine, it doesn't see the RP1. 

My question is: is it possible to have both adb working, and connect to the app using usb? If not, is it possible to switch between them?

**Comment by HappyZ** [comment]
If you did it very early, I suggest you to redo the hack, as it has been
advanced a lot now. To answer your question, yes, adb and USB should both
work at the same time.

The only problem goes with MacOS driver, where you have to logout and
re-login to use adb.

**Comment by robertsjchen** [comment]
yes. @HappyZ  is right. I met same issue before, just redo the hack, now adb works as expected! thanks HappyZ!

**Comment by HappyZ** [comment]
Assuming @ghostwheel issue has gone. Please re-open if you still have the problem.

**Comment by seanlvjie** [comment]
@HappyZ 
I've similiar condition as @ghostwheel 
I rooted my RP1 around Feb 2019, and then followed your advice and redo the hack again today, so that it's expected I could get USB DPA and USB ADB at the same time.  

Unfortunately, I still can NOT use DPA via USB as same as before.  I am using MacOS with following env
=>Digital Paper App： Version1.4.3.17290  
=>DPT-RP1 ：Version 1.6.03.09261 (Updated from 1.4.01.16100 yesterday)

Could you please help me ?
