### ISSUE TITLE
Locally Loading PDF into Digital Paper PDF Reader

### ISSUE THREAD

**Issue by wart-github** [HappyZ/dpt-tools#135]
Hi,

First things first, excellent work! 

Has anyone figured out how to load a pdf into the digital paper pdf reader locally?  For instance, if I download a pdf on the DPT RP1 itself in Fennic Firefox or in a Mail App on the DPT RP1, how can I "share" it over to the PDF reader on the DPT RP1?  I did some digging and the file structure is pretty opaque.  (One option I thought of was installing dpt-rpt-py on the DPT RPT itself, but I thought I'd ask if anyone has implemented something first.)

Thanks for any tips

**Comment by HappyZ** [comment]
One way is you write an Android app/plugin on some PDF app for DPT that supports to download/upload files based on DPT app's API.. it's the most intuitive workaround I can think of

**Comment by aluex** [comment]
Maybe the official android app will work?

**Comment by JoeKays** [comment]
The official android app does not work because it requires Android version >6 and the DPT has only 5.
Also it doesn't seem possible to use dpt-rp1-py with qpython because the crypto packages do not install on the DPT.

So that means that there is only one solution: rewriting dpt-rp1-py in javascript and using it from the browser (or package it into an apk with WebView). I am currently working on this port. So far I am able to authenticate and list documents from my computer. Next step is uploading pdfs and somehow hosting the page on the DPT so I can access the page from the browser there.

**Comment by JoeKays** [comment]
Update: I succeeded in uploading and downloading pdfs from my chrome browser!
Only thing that is left for now is to try hosting the site on the DPT. Because so far I accessed the page from the DPT but I hosted it on my computer.
But I guess that's not gonna be the biggest problem and soon we will be able to locally load pdfs to the device! :D

**Comment by HappyZ** [comment]
Pretty coooool

**Comment by JoeKays** [comment]
Update: check out the initial release on https://github.com/JoeKays/dpts

Hope it works :)

**Comment by JoeKays** [comment]
Update: There is an update available, check it out! :D

This update removes most of the limitations and makes the tool quite usable I would say.
You can upload and download documents, create folders and delete them. All from the DPT and also from your computer if you like. You only need a browser and some patience for the setup.

Only real problem is that USB only works on Linux. You have to use WiFi on Windows and Mac. I would love it if someone could help me with making it work on these platforms. I don't have any such device available at the moment...
