### ISSUE TITLE
Access pdf files uploaded with sony DPA 

### ISSUE THREAD

**Issue by itskalvik** [HappyZ/dpt-tools#174]
Is there a way to properly open files transferred with the Sony Digital Paper App? I was able to find the pdf files with the koreader's file manager but, the file names are different from what I see in the sony file manager.

**Comment by JoeKays** [comment]
I suppose that using the files from the DPT's storage directly is not the best approach, because of the problems you mentioned.

If you want to 'download' files from the DPT's storage to the device locally you could use my little tool: https://github.com/JoeKays/dpts

Other options include using https://github.com/janten/dpt-rp1-py and transferring the file to your PC first.
