### ISSUE TITLE
can't flash pkg - even official 1.4 firmware -- error 90001

### ISSUE THREAD

**Issue by ziegfeld** [HappyZ/dpt-tools#19]
Dear HappyZ,

I have followed the README and some hi-pda e-ink bbs posts and successfully patched my boot.img and rooted my DPT-RP1.
Great job! Really appreciate your work!

Problem now is that I am trying to use "dpt-tools.py" `fw` mode 
1. to flash the official SONY firmware. but after the script in terminal finished normall,y the device reboots, then a "verfiying package" message is there. but afterwards it goes to a "cannot upgrade. error code 900001".

2. if I use my own modified pkg, it would be similar to the above, but even without the "veryfiying package part", straght to 90001 after a few screen blinks. (I would also mention that, when I use your unofficial repacker to generate this .pkg file. on one step the sdtout/stderr showed "Verification Failure", I guess from openssl")

Would you kindly provide some insights? Thank you!

Regards,
Ziegfeld

**Comment by ziegfeld** [comment]
I would add that -- previously when I did "dpt-tools.py" "root", I saw 90001 and update failure errors too, just as many pals in hi-pad e-ink bbs. But still the root worked, I even successfully added busybox.

**Comment by HappyZ** [comment]
The update failure 90001 error is expected. It is the error comes from the missing signals that acknowledge the success of fw updates. For example, if your system is already updated to 1.4.abcd, when you flash that 1.4.abcd pkg again, it will show this failure msg. Similarly, since rooting pkg isn't a real pkg, it didn't alert the system the success of fw update.

And yes, the verification failure message is only a warning. If you modified the updater.sh in your system, the system will flash the pkg, bypassing verifications, even though 90001 message shows.

**Comment by HappyZ** [comment]
Actually, it'll depend on the script in pkg. If there is a version check bash like the official pkg does, then when you run it, it will stop upgrading.

**Comment by ziegfeld** [comment]
Got it. I will modify the updater.sh.

Thank you so much for replying, yanzi!

I did not modify the updater.sh because I cannot see it; then someone told me I need to mount system partition first.. I missed that part.
So it would also be great, if you can add that line to mount the system so that /usr/shared/bin/ can be viewed. In your README at https://github.com/HappyZ/dpt-tools/blob/master/fw_updater_packer_unpacker/README.md 

```
mkdir /mnt/system
mount -t ext4 /dev/mmcblk0p9 /mnt/system
```

**Comment by HappyZ** [comment]
I have added the method in diagnosis mode. It's `patch-updater-bash` command.
