### ISSUE TITLE
about xposedinstall

### ISSUE THREAD

**Issue by yefeiyu** [HappyZ/dpt-tools#191]
When I installed Xposedinstaller, It is told me "Xposed framework is not installed" .
I also did the supersu step use "fw", how do i see if it works?

**Comment by stanleyws** [comment]
[xposed.zip](https://github.com/HappyZ/dpt-tools/files/10356797/xposed.zip)
[com.skyolin.helper_v1250_f9172d.zip](https://github.com/HappyZ/dpt-tools/files/10356811/com.skyolin.helper_v1250_f9172d.zip)


You can't download xposed framework installer zip or plugins in xposed app anymore because the domain hosting the repo (xposed.info) has been offline since July. I faced the same problem when modding another dpt-rp1 several months ago. Attached is my modded xposed installer, I removed all checks that won't work outside of custom recovery and you just need to upload it to your dpt, exctact it and execute "sh flash-script.sh" with su in terminal. You should see "Done" if everything worked, your dpt will reboot shortly after and xposed framework should be installed. 


I also attached skyolin helper plugin which I use to change per app dpi, I pulled it from my other dpt-rp1's cache folder together with the xposed installer zip. They should be the latest version as of 2021 when I modded my first dpt-rp1.

**Comment by yefeiyu** [comment]
> [xposed.zip](https://github.com/HappyZ/dpt-tools/files/10356797/xposed.zip) [com.skyolin.helper_v1250_f9172d.zip](https://github.com/HappyZ/dpt-tools/files/10356811/com.skyolin.helper_v1250_f9172d.zip)
> 
> You can't download xposed framework installer zip or plugins in xposed app anymore because the domain hosting the repo (xposed.info) has been offline since July. I faced the same problem when modding another dpt-rp1 several months ago. Attached is my modded xposed installer, I removed all checks that won't work outside of custom recovery and you just need to upload it to your dpt, exctact it and execute "sh flash-script.sh" with su in terminal. You should see "Done" if everything worked, your dpt will reboot shortly after and xposed framework should be installed.
> 
> I also attached skyolin helper plugin which I use to change per app dpi, I pulled it from my other dpt-rp1's cache folder together with the xposed installer zip. They should be the latest version as of 2021 when I modded my first dpt-rp1.

Thank you very much! It works!
Now I have other two question:
1. Why is the Eink-launcher not working properly? It can be used by clicking to open it, but it cannot be used as a default desktop program.
2. I turned on the switch for programs from unknown sources, but I can't install the program through Fdroid, and I can't install the program after uploading to rp1's /sdcard .
