### ISSUE TITLE
diff of whole system

### ISSUE THREAD

**Issue by sekkit** [HappyZ/dpt-tools#38]
[dir3.txt](https://github.com/HappyZ/dpt-tools/files/2682616/dir3.txt)
[dir4.txt](https://github.com/HappyZ/dpt-tools/files/2682617/dir4.txt)
this is the md5 output of original firmware/ hacked one.
using Beyond Compare or other diff tools to see the differences.

**Comment by hitmoon** [comment]
After a quick view, I will say both two files are not from original firmware. dir3.txt is definitely from hacked firmware, because I can see applauncher.apk, which is used by taobao version to launcher manually installed app (I also use it personally). dir4.txt contains xposed framework and daemonsu, su , so it will also not from original firmware.
