### ISSUE TITLE
Cannot flash modified boot.img to obtain ADB access

### ISSUE THREAD

**Issue by tartakis** [HappyZ/dpt-tools#42]
I am stuck at the above step. My steps:
1. Issue `restore-bootimg` command
2. Copy `boot-1.4.01.16100-mod-happyz-181214.img` to the attached mass storage device, rename it to `boot.img.bak`, eject mass storage device, press return
3. The script reports the md5 checksum of the `boot.img.bak` file I backed-up with `backup-bootimg` command before and not of the new file

Any ideas?

Thanks!

**Comment by HappyZ** [comment]
it's probably due to unsuccessful umount in the tool which didn't check properly. Have you patched the updater bash? If so, you can directly flash the pkg with this boot img in the normal boot up mode. It's at https://github.com/HappyZ/dpt-tools/tree/master/fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img

another way is to reboot into diagnosis mode and retry the restore without copying the file

**Comment by tartakis** [comment]
I seem to have resolved the issue by issuing `rm boot.img.bak` from the command line in the diagnosis mode. When the mass storage device appeared, the file `boot.img.bak` was still there! But this time the right file (judged from the md5 checksum) was flashed.
