### ISSUE TITLE
Is there a way to upload pdf files to the device after rooting using the modified boot.img in the repo?

### ISSUE THREAD

**Issue by art-repertoire** [HappyZ/dpt-tools#54]
I have successfully rooted my DPT-RP1 and I can use adb commands. I am aware that I cannot use DPA with the modified boot.img. Is there a way to upload pdf files without DPA? Thanks!

**Comment by HappyZ** [comment]
You should be able to use bluetooth or wifi to connect to DPA. You can also use [janten's tool](https://github.com/janten/dpt-rp1-py) to upload docs.

Sorry, I haven't get time to look into this yet.

**Comment by qz-lab** [comment]
> I have successfully rooted my DPT-RP1 and I can use adb commands. I am aware that I cannot use DPA with the modified boot.img. Is there a way to upload pdf files without DPA? Thanks!

Same problem. Digital Paper App can not connect to the dpt-rp1 through USB, bluetooth or WIFI.

Everything went well when I first hacked my dpt-rp1, but when I tried to upload a pdf yesterday, the App didn't work. I'm not sure when the App started to not recognize the device.

I recommend to use koreader and you can upload files through `adb push`. Refer to #48.

**Comment by art-repertoire** [comment]
Thanks HappyZ and Zack-Q! I managed to use DPA via WIFI. It is not as convenient as using DPA via USB, but I can live with it now : )

**Comment by qz-lab** [comment]
May I ask how you did it ? @art-repertoire

**Comment by HappyZ** [comment]
@Zack-Q when you say it doesn't work for all connections, did it work before? Anything done in between?

**Comment by art-repertoire** [comment]
> 
> 
> May I ask how you did it ? @art-repertoire

1) Connect your computer and your DPT-RP1 device to the same WIFI access point. 2) Open DPA, it will try to connect the device.

**Comment by qz-lab** [comment]
@HappyZ I can't remember I have done anything special since I rooted the device.

For your information, I rooted the device, then flashed **the TaoBao image**. Since it didn't work, I flashed **the official image** back. I lost all my pdfs on the device, so I used the app to synchronize my backup to the device (The app did work at that time). After I installed **koreader**, I kept using `adb push` to transfer files. A few days ago, I tried to use the app and found it could not recognize the device any more, for all connections.

**Comment by HappyZ** [comment]
> @HappyZ I can't remember I have done anything special since I rooted the device.
> 
> For your information, I rooted the device, then flashed **the TaoBao image**. Since it didn't work, I flashed **the official image** back. I lost all my pdfs on the device, so I used the app to synchronize my backup to the device (The app did work at that time). After I installed **koreader**, I kept using `adb push` to transfer files. A few days ago, I tried to use the app and found it could not recognize the device any more, for all connections.

I can't repeat this right now. But, if you use the old modded `boot.img` version (Nov version), would it work?

**Comment by qz-lab** [comment]
I flashed the `boot-1.4.01.16100-mod-happyz-181118.img`, but the device still can't be recognized.

It's been a while since I rooted my device, so I list the steps here so that you can see if I did it wrong.

1. Enter the dpt-tools directory and run `python3 dpt-tools.py ...`.
2. Run the command `diagnosis`, follow the instructions, reboot the device to the diagnosis mode.
3. Run the command `restore-bootimg` in the diagnosis mode.
4. Follow the instructions to copy the file `python_api/assets/boot-1.4.01.16100-mod-happyz-181118.img` into the newly mounted disk, rename it to `boot.img.bak`. Press the enter key and start to flash.
5. Reboot the device.

Thanks.

**Comment by HappyZ** [comment]
closed as this is the same issue #58
