### ISSUE TITLE
recover to official default

### ISSUE THREAD

**Issue by nyanadassana** [HappyZ/dpt-tools#62]
Hello, can anyone share how can I recover my rp1 back into official default? I have connection problems now and I can't read files via both MacOS and Windows. Thanks.
I have read #31, but I don't understand this:
"If you can still connect via normal boot, use official fw flashing."

**Comment by HappyZ** [comment]
Are you able to connect wirelessly? And did you flash the system img shared
by the community?

Can you flash the official boot img to see if the problem persists? You
should have your backed up boot img.

If it's not working, I suspect other issues rather than boot img. You can
try to reset first to see if problem is gone.

If not, I'll write a tutorial this weekend to allow you flash back to
official. The official PKG has a verification script so you can't directly
flash it.


Yz

**Comment by nyanadassana** [comment]
I can't get any connection via bluetooth nor wifi nor usb. I flashed the original system.img md5=a35d6d6697b637184aeb41b4f356ff95 
but after I flash back my backup boot.img, the connection come back!
thanks for your advice.

**Comment by nyanadassana** [comment]
update: after few hours, it fails again.

**Comment by HappyZ** [comment]
But the authentication in my script `dpt-tools.py` or janten's script still work? 

And can you still see yours in `adb devices`?

**Comment by nyanadassana** [comment]
yes, dpt-tools.py still work, so I tried my different system.img, until just now I re-flash the original system.img I mentioned before. suddenly it can connect again. 
no devices when I try adb devices. I didn't see my device in adb for a Long time.
update : after few hours, again it can't connect with the DPA.
@HappyZ I need your help to flash back to original pkg. Thanks you!

**Comment by nyanadassana** [comment]
again it not working. ::-\

**Comment by HappyZ** [comment]
this behavior turns into a complete myth.. if authentication still works, then DPA must be broken in some other manner.. there must be something (app, process) that kills the function of DPA.. I need a log dump of DPA but that'll wait till I got time to do it.. 

I'll remove the verifications script and make two flashable PKGs that reset the boot partition as well as the system partition. But it seems the issue comes from user space, not system/boot partitions. So you may want to do a reset before you restore, as simply restoring the system may not fix your issue. 

The modded officials that bypass version check can be downloaded at https://github.com/HappyZ/dpt-tools/wiki/PKGs-I-Made/

**Comment by nyanadassana** [comment]
thank you very much!
I boot into the diagnosis mode, And  I did the the factory reset by: /usr/local/bin/factory_reset.sh 
 mount the storage partition by boot-recover, 
copy the official PKGs modified by happyZ.
reboot. 
now it's working! thanks again

**Comment by HappyZ** [comment]
I actually hope you did only the first part (reset) and see if issue is fixed, so it helps on others.. but well, anyway

**Comment by nyanadassana** [comment]
previously I already tried reset the dpt, but it won't solve the problem at all.
