### ISSUE TITLE
Can't get root to work

### ISSUE THREAD

**Issue by oddpixels** [HappyZ/dpt-tools#9]
Hi,
first of all, thank you for your effort and great work!
Unfortunately, I can't seem to get this to work. After entering "root" I get the following output:
```
>>> root
[info] Please make sure you have charged your battery before this action.
[info] Thank shankerzhiwu (and his/her anonymous friend) a lot on this hack!!!All credits go to him (and his/her anonymous friend)!
>>> Have you disabled the id check already? [yes/no]: no
>>> Press `Enter` key to continue after your DPT reboot, shows `update failure` message, and con[info] Congrats! You are half-way through! You have disabled the OTG ID check
[error] https://192.168.111.53:8443/system/controls/update_firmware/file
[error] request error 401:
[error] * error_code: 40100
[error] * message: Authentication is required.
[error] failed to upload file
[error] Failed to upload shankerzhiwu_changepwd pkg
```
Any advice would be much appreciated.

**Comment by HappyZ** [comment]
So you have passed the first step to disable id check I assume. 

Did you wait until it boots up, saying update failure, and connected to wifi? If so, you should be able to do the second step. Run the tool again, let it pass authentication check, and type in `root`. Then type `yes` since you already disabled the id check. 

The authentication failure happens due to either 1) unstable connection or no connection; 2) you did not wait until it fully boots up; or 3) you did not provide the correct key info

**Comment by oddpixels** [comment]
Thanks for your response.
I had the same suspicions about the cause of this error. So to check after the reboot I first tried to connect using the script from Janten by running the list-documents command which worked.
So it seems to me that the connection worked and the key is good, isn’t it?

**Comment by HappyZ** [comment]
Yea, you can just say `yes` to the first question and do the second step. It should work fine.

**Comment by oddpixels** [comment]
Thanks. Got it working. Only "issue" was that I had to try a few times in order for the login to work in diagnosis mode. But now everything works.

**Comment by HappyZ** [comment]
Glad to know it works for you! Happy Thanksgiving!
